---
# Role task

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      fedora: 27
      rhel: 6

- include_role:
    name: amtega.packages
  vars:
    packages_os:
      all:
        all:
          ntp: present
          chrony: absent
          ntpdate: present

- name: Configure timezone
  include_tasks: timezone.yml
  tags:
    - role::ntp
    - role::ntp::configure
    - role::ntp::timezone

- name: Configure ntp daemon
  include_tasks: ntp.yml
  tags:
    - role::ntp
    - role::ntp::configure

- name: Configure ntpdate
  include_tasks: ntpdate.yml
  tags:
    - role::ntp
    - role::ntp::configure
    - role::ntp::ntpdate
