---
# Role task

- name: Configure system timezone
  include_tasks: timezone.yml
  tags:
    - role::ntp
    - role::ntp:timezone

- name: Configure ntp daemon
  include_tasks: ntp.yml
  tags:
    - role::ntp
    - role::ntp::configure

- name: Configure ntpdate
  include_tasks: ntpdate.yml
  tags:
    - role::ntp
    - role::ntp::ntpdate
