---

- name: Configure ntp
  block:
    - name: Setup ntp config file
      ansible.builtin.template:
        src: ntp.conf.j2
        dest: "{{ ntp_config_file }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - enable ntp service

    - name: Configure ntp init options
      ansible.builtin.template:
        src: ntpd_sysconfig.j2
        dest: "{{ ntp_sysconfig_file }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - enable ntp service

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Ensure ntpdate daemon is stopped before activate ntp
      ansible.builtin.service:
        name: ntpdate
        state: stopped
        enabled: no
      when:
        - '"ntpdate.service" in ansible_facts.services.keys() | list'
        - ntp_clock_sync
  tags:
    - role::ntp
    - role::ntp::configure
