---
# Tasks to configure ntp

- block:
    - name: Setup ntp config file
      template:
        src: ntp.conf.j2
        dest: "{{ ntp_config_file }}"
      notify:
        - enable ntp service

    - name: Configure ntp init options
      template:
        src: ntpd_sysconfig.j2
        dest: "{{ ntp_sysconfig_file }}"
      notify:
        - enable ntp service

    - name: Gather service facts
      service_facts:

    - name: Ensure ntpdate daemon is stopped before activate ntp
      service:
        name: ntpdate
        state: stopped
        enabled: no
      when:
        - '"ntpdate.service" in ansible_facts.services.keys() | list'
        - ntp_clock_sync
  tags:
    - role::ntp
    - role::ntp::configure
