---

- name: Configure ntpdate
  block:
    - name: Create directory for ntpdate config file
      ansible.builtin.file:
        path: "{{ ntpdate_config_file | dirname }}"
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Setup ntpdate config file
      ansible.builtin.template:
        src: ntpdate_config.j2
        dest: "{{ ntpdate_config_file }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - enable ntpdate service

    - name: Setup ntpdate init options
      ansible.builtin.template:
        src: ntpdate_sysconfig.j2
        dest: "{{ ntpdate_sysconfig_file }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - enable ntpdate service

    - name: Ensure ntp daemon is stopped before activate ntpdate
      ansible.builtin.service:
        name: ntpd
        state: stopped
        enabled: no
      when:
        - '"ntpd.service" in ansible_facts.services.keys() | list'
        - not ntp_clock_sync
  tags:
    - role::ntp
    - role::ntp::configure
    - role::ntp::ntpdate
