---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          ntp_clock_sync: yes
          ntp_slew_mode: yes
verifier:
  name: ansible
