---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  ${MOLECULE_SCENARIO_DIRECTORY}/molecule_linters.sh
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    box: centos/6
    memory: 1024
    provider_options:
      gui: false
    provider_raw_config_args:
      # Disable video
      - 'customize ["modifyvm", :id, "--graphicscontroller", "none"]'
      - 'customize ["modifyvm", :id, "--vram", "0"]'
      # Disable audio
      - 'customize ["modifyvm", :id, "--audio", "none"]'
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 1024
    provider_options:
      gui: false
    provider_raw_config_args:
      # Disable video
      - 'customize ["modifyvm", :id, "--graphicscontroller", "none"]'
      - 'customize ["modifyvm", :id, "--vram", "0"]'
      # Disable audio
      - 'customize ["modifyvm", :id, "--audio", "none"]'
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "fedora32-${INSTANCE_UUID:-1}"
    box: fedora/32-cloud-base
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_32
  - name: "fedora33-${INSTANCE_UUID:-1}"
    box: fedora/33-cloud-base
    memory: 1024
    provider_options:
      gui: false
    provider_raw_config_args:
      # Disable video
      - 'customize ["modifyvm", :id, "--graphicscontroller", "none"]'
      - 'customize ["modifyvm", :id, "--vram", "0"]'
      # Disable audio
      - 'customize ["modifyvm", :id, "--audio", "none"]'
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          ntp_clock_sync: true
verifier:
  name: ansible
