---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: molecule_hosts
  become: yes
  tasks:
    - name: Pause to wait for ntp synchronization
      pause:
        minutes: 1

    - name: Check if ntp is running an synchronized
      command: ntpstat
      register: ntp_check
      changed_when: no
      failed_when: >-
        not ntp_check.stdout
        is search("synchronised to NTP server")
      when: ntp_clock_sync
    - name: Check ntpd is running in slew mode (ntpd -x)
      shell: |-
        set -o pipefail
        ps aux \
        | grep "[n]tpd.* -x$"
      changed_when: no
      register: ntpd_in_slew_mode_result
      failed_when: >-
        ntp_in_slew_mode and ntpd_in_slew_mode_result.rc != 0
        or not ntp_in_slew_mode and ntpd_in_slew_mode_result.rc == 0
